import type { Metadata } from "next";
import { Geist, Geist_Mono, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import RestaurantFooter from "@/components/RestaurantFooter";
import { ReduxProvider } from "@/lib/redux/ReduxProvider";
import RestaurantNavbar from "@/components/RestaurantNavbar";
import { ToastProvider } from "@/lib/context/ToastContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sourceSans.variable} antialiased`}
      >
        <ReduxProvider>
          <ToastProvider>
            <RestaurantNavbar />
            {children}
            <RestaurantFooter />
          </ToastProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
